"""Catálogo de nombres para las 184 bandas del mosaico SBAND-184B (índice rasterio 1-based)."""

from __future__ import annotations

# Orden estable del stack HARM/RF (band_0 … band_183 ↔ rasterio 1 … 184).
NOMBRES_BANDAS_RF: tuple[str, ...] = (
    "aspect",
    "blue_amp",
    "blue_max",
    "blue_median",
    "blue_median_dry",
    "blue_median_wet",
    "blue_min",
    "blue_stdDev",
    "cai_amp",
    "cai_max",
    "cai_median",
    "cai_median_dry",
    "cai_median_wet",
    "cai_min",
    "cai_stdDev",
    "cloud_amp",
    "cloud_max",
    "cloud_median",
    "cloud_median_dry",
    "cloud_median_wet",
    "cloud_min",
    "cloud_stdDev",
    "elevation",
    "evi2_amp",
    "evi2_max",
    "evi2_median",
    "evi2_median_dry",
    "evi2_median_wet",
    "evi2_min",
    "evi2_stdDev",
    "fns_amp",
    "fns_max",
    "fns_median",
    "fns_median_dry",
    "fns_median_wet",
    "fns_min",
    "fns_stdDev",
    "gcvi_amp",
    "gcvi_max",
    "gcvi_median",
    "gcvi_median_dry",
    "gcvi_median_wet",
    "gcvi_min",
    "gcvi_stdDev",
    "green_amp",
    "green_max",
    "green_median",
    "green_median_dry",
    "green_median_texture",
    "green_median_wet",
    "green_min",
    "green_stdDev",
    "gv_amp",
    "gv_max",
    "gv_median",
    "gv_median_dry",
    "gv_median_wet",
    "gv_min",
    "gv_stdDev",
    "gvs_amp",
    "gvs_max",
    "gvs_median",
    "gvs_median_dry",
    "gvs_median_wet",
    "gvs_min",
    "gvs_stdDev",
    "hallcover_amp",
    "hallcover_max",
    "hallcover_median",
    "hallcover_median_dry",
    "hallcover_median_wet",
    "hallcover_min",
    "hallcover_stdDev",
    "hallheigth_amp",
    "hallheigth_max",
    "hallheigth_median",
    "hallheigth_median_dry",
    "hallheigth_median_wet",
    "hallheigth_min",
    "hallheigth_stdDev",
    "mbi",
    "ndbi",
    "ndfi_amp",
    "ndfi_max",
    "ndfi_median",
    "ndfi_median_dry",
    "ndfi_median_wet",
    "ndfi_min",
    "ndfi_stdDev",
    "ndmi",
    "ndsi",
    "ndvi_amp",
    "ndvi_max",
    "ndvi_median",
    "ndvi_median_dry",
    "ndvi_median_wet",
    "ndvi_min",
    "ndvi_stdDev",
    "ndwi_amp",
    "ndwi_max",
    "ndwi_median",
    "ndwi_median_dry",
    "ndwi_median_wet",
    "ndwi_min",
    "ndwi_stdDev",
    "nir_amp",
    "nir_max",
    "nir_median",
    "nir_median_dry",
    "nir_median_wet",
    "nir_min",
    "nir_stdDev",
    "npv_amp",
    "npv_max",
    "npv_median",
    "npv_median_dry",
    "npv_median_wet",
    "npv_min",
    "npv_stdDev",
    "pri_amp",
    "pri_max",
    "pri_median",
    "pri_median_dry",
    "pri_median_wet",
    "pri_min",
    "pri_stdDev",
    "red_amp",
    "red_max",
    "red_median",
    "red_median_dry",
    "red_median_wet",
    "red_min",
    "red_stdDev",
    "savi_amp",
    "savi_max",
    "savi_median",
    "savi_median_dry",
    "savi_median_wet",
    "savi_min",
    "savi_stdDev",
    "sefi_amp",
    "sefi_max",
    "sefi_median",
    "sefi_median_dry",
    "sefi_median_wet",
    "sefi_min",
    "sefi_stdDev",
    "shade_amp",
    "shade_max",
    "shade_median",
    "shade_median_dry",
    "shade_median_wet",
    "shade_min",
    "shade_stdDev",
    "slope",
    "soil_amp",
    "soil_max",
    "soil_median",
    "soil_median_dry",
    "soil_median_wet",
    "soil_min",
    "soil_stdDev",
    "swir1_amp",
    "swir1_max",
    "swir1_median",
    "swir1_median_dry",
    "swir1_median_wet",
    "swir1_min",
    "swir1_stdDev",
    "swir2_amp",
    "swir2_max",
    "swir2_median",
    "swir2_median_dry",
    "swir2_median_wet",
    "swir2_min",
    "swir2_stdDev",
    "tpi",
    "wefi_amp",
    "wefi_max",
    "wefi_median",
    "wefi_median_dry",
    "wefi_median_wet",
    "wefi_min",
    "wefi_stdDev",
)


def nombre_banda_rasterio(indice_rasterio: int) -> str:
    """Nombre de banda para índice rasterio 1-based."""
    if 1 <= indice_rasterio <= len(NOMBRES_BANDAS_RF):
        return NOMBRES_BANDAS_RF[indice_rasterio - 1]
    return f"banda_{indice_rasterio:03d}"


def nombres_bandas_mosaico(n_bandas: int, descripciones: tuple[str, ...] | None = None) -> list[str]:
    """Lista de nombres de columnas para un stack de ``n_bandas`` canales."""
    if descripciones and len(descripciones) >= n_bandas:
        out = []
        for i in range(n_bandas):
            d = descripciones[i]
            out.append(d if d else nombre_banda_rasterio(i + 1))
        return out
    return [nombre_banda_rasterio(i + 1) for i in range(n_bandas)]
